name: test doc readme  #ten quy trinh

on:          #Chay khi nao
  push:
      branches: {"main"}    #khi push len nhanh main

jobs:
  Thuc_hanh_doc_file:
      runs-on: ubuntu-lastest    #Muon may ao

      steps: 
        - name: Buoc 1  - Xin chao        #Lenh in ra man hinh
          run!: echo "Hello HUTECH"

        -name:  Buoc 2 - Tai code         #Robot tu dong copy code vao may ao
          uses: actions/chechout@v6.0.2

        -name:  Buoc 3 - Doc file         #Mo noi dung file README.md de xem
          run!: cat README.md
